- src/cookies.ts
- tsconfig.json
There was a type script issue in `master` blocking the code compiling, this change fixes that. It only surfaced after `yarn build`, so I need to look into why `yarn lint` didn't pick it up, but I'll do that as part of the `eslint` switch over work!
> fix tsconfig build issues

- src/cookies.ts
Removes unnecessary isCookieSubdomain from cookies.js as all our cookies will be cross-domain.
> Removed isCookieSubdomain from cookies.js

- .eslintrc.json
- .vscode/extensions.json
- package.json
- Inverted the order of the two commands ran by prepublishOnly
- Added myself to contributors
- Added eslint to vscode suggested plugins
- Added `@typescript-eslint/prefer-interface` lint rule
> Boilerplate changes

- package.json
- tc-validate.sh
- validate.sh
This PR introduces the script `tc-validate.sh`. This script is executed by Teamcity, our continuous integration server whenever a push is made to a branch. The script runs `yarn validate` (which runs the `tsc` typescript compiler command and `eslint`) and `yarn test` which runs our jest unit tests.
> Teamcity integration script

- package.json
- src/cookies.test.ts
- src/cookies.ts
- yarn.lock
This PR introdices the js-cookie library. This provides a simple API for saving and retrieving cookies, it is lightweight (g-zipped ~1.1k) and it ensures the values saved are [RFC-6265](https://tools.ietf.org/html/rfc6265#section-4.1.1) compliant.
> Use js-cookie library

- src/cookies.test.ts
- src/cookies.ts
- src/index.d.ts
Update interface of cookies.ts to expose 4 functions:
- readGuCookie
- readIabCookie
- writeGuCookie
- writeIabCookie
Inspired by https://github.com/guardian/manage-frontend/pull/261
> Update interface of cookies.ts

- README.md
- docs/01-development-instructions.md
- package.json
- src/cmp.test.ts
- src/cmp.ts
- src/config.ts
- src/cookies.test.ts
- src/cookies.ts
- src/index.d.ts
This PR copies the `cmp` module from frontend into the library (earlier PR adding it to frontend is here: https://github.com/guardian/frontend/pull/21705).  The plan is to remove it from frontend and start using the library in it's place.
> Introduce cmp module to library

- src/config.ts
- src/index.d.ts
Adding shared types and variables that currently live in manage-frontend so that the CMP UI can instead import them from this library.
> Add types and variables needed for CMP UI

- package.json
Bumps version to 0.1.0-alpha2 as well as update the build command so the type definition is included in the build.
> Bump version to 0.1.0-alpha2

- .eslintrc.json
- jestconfig.json
- package.json
- yarn.lock
This PR makes the following changes:
- Upgrade `@typescript-eslint/eslint-plugin` to: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.1.0
- Upgrade `eslint` to: https://github.com/eslint/eslint/releases/tag/v6.3.0 
These dependencies needed updating as they include a vulnerable sub-dependency `eslint-utils@1.4.0`: https://github.com/mysticatea/eslint-utils/security/advisories/GHSA-3gx7-xhv7-5mx3
> Bump versions of @typescript-eslint/eslint-plugin and eslint

- src/cmp.ts
- src/types.ts
We use `boolean | null` for states in a lot of places. Better to have a type for it  instead of retyping it every time. Also better if we ever need to change this type.
> Replace boolean | null with ItemState type

- src/config.ts
- src/cookies.test.ts
- src/cookies.ts
- src/types.ts
Introduce a version number to the GU cookie so we can differentiate between version if we want to change the cookie structure at a later date.
> Introduce version number to GU cookie

- src/config.ts
- src/index.ts
...so that it's available to any platforms that need to show the CMP UI. Also removes some unnecessary items from the `cmpConfig` object we expose in the package.
> Expose CMP_URL as a package constant

- README.md
- src/cmp.test.ts
- src/cmp.ts
- src/config.ts
- src/types.ts
- Replace `purposes` in `./cmp.ts` with `guPurposeRegister` and `iabPurposeRegister`.
- Construct `guPurposeRegister` using the `GU_PURPOSE_LIST`  from `./config.ts`.
- We now have two new methods exposed on the interface of `./cmp.ts`, `onIabConsentNotification` and `onGuConsentNotification`, these replace the method `onConsentNotification`.
> Refactor cmp.ts

- src/config.ts
This PR updates the config so if the library is running on a `CODE`/`DEV` domain it uses the CODE domains for CMP UI and Vendor list endpoint.
> If running on CODE/DEV use the CODE domains for CMP UI and Vendor list

- package.json
- src/cmp.test.ts
- src/cmp.ts
- yarn.lock
This PR updates the `cmp.ts` module. 
Callbacks currently passed to `onIabConsentNotification` are executed with the `iabPurposeRegister.state` as their first argument. Currently the value of `iabPurposeRegister.state` is derived from the `GU_TK` cookie. For example, If `GU_TK === '1.54321'` then `iabPurposeRegister.state = {1: true, 2: true, 3: true, ...}` OR If `GU_TK === '0.54321'` then `iabPurposeRegister.state = {1: false, 2: false, 3: false, ...}`.
This PR updates the `cmp.ts` module so callbacks passed to `onIabConsentNotification` are now executed with an `iabPurposeRegister.state` derived from the IAB string cookie if it exists. If the IAB string cookie does not exist then we then fallback to trying the `GU_TK` cookie (as before).
> onIabConsentNotification return IAB state derived from IAB Cookie if available

- package.json
- src/cmp-ui.ts
- src/config.ts
- src/consent-storage.ts
- src/consent-store.ts
- src/cookies.ts
- src/types.ts
This PR does two things:
- Refactors the code that saves and logs the consent state
- Adds saving the GU_TK cookie (So that consent state remains consistent after the CMP test ends)
> Refactor save/log consent state

- src/cmp.test.ts
- src/cmp.ts
- src/config.ts
- src/cookies.test.ts
- src/cookies.ts
Pulls the temporary legacy cookie reading code into `cookie.ts` by exposing new `readLegacyCookie` function on it.
> Pull the temporary legacy cookie reading code into cookie.ts

- package.json
- src/consent-storage.ts
- src/types.ts
Currently we've hardcoded the value of `variant` in the consent log data to be 'CmpUiIab-variant', this PR changes that so instead we set the value of `variant` to the value of `abTestVariant`, a new property that the CMP UI includes in the `CMP_SAVED_MSG` post message.
> Handle abTestVariant in CmpMsgData

- src/component/ConsentManagementPlatform.tsx
- src/logs.ts
- src/store.test.ts
- src/store.ts
This PR executes phase five of the CMP restructure, which includes:
- Pass variant into the UI component, save it in `store.ts` and send it in the logs
- Pass source into the UI component, save it in `store.ts` and send it in the logs
- Expose a `getVariant()` function in `store.ts` 
- Add unit tests for the new functions
Notes:
- Moved some code around inside `store.ts` to improve its organisation, such as grouping similar variables together and grouping setter and getter functions.
- Fixed an issue in `logs.ts` that would send an empty string in the variant when the value passed is null or undefined. It now removes the field from the payload entirely, as expected by the consent logs API.
> CMP restructure phase 5

- src/component/CmpCollapsible.tsx
- src/component/ConsentManagementPlatform.tsx
- src/component/ConsentPreferencesDashboard.tsx
- src/component/FontsContext.tsx
- src/component/OnOffRadio.tsx
- src/component/utils/config.ts
- src/types.ts
Currently the `font-family` names we use in the CSS-in-JS for the CMP UI component are hardcoded to be the same as the `font-family` names used on `frontend`. 
Unfortunately, although the font files on `frontend` are up to date the `font-family` names it uses are the out of date legacy `font-family` names. For example...
Legacy headline font-family: `Guardian Egyptian Web, Georgia, serif`
Up to date headline font-family: `GH Guardian Headline, Georgia, serif` 
Other platforms on which the new CMP UI will run (dotcom-rendering for example) use the up to date files AND the up to date `font-family` names too.
This PR updates the `<ConsentManagementPlatform>` component to take a new prop `fontFamilies`. This optional prop looks like:
```js
<ConsentManagementPlatform fontFamilies={{ …
```
> Introduce FontsContext (CMP restructure)

- src/component/ConsentPreferencesDashboard.tsx
- src/error.test.ts
- src/error.ts
- src/index.ts
- src/logs.test.ts
- src/logs.ts
- src/store.test.ts
- src/store.ts
This PR executes phase six of the CMP restructure, which includes:
- Add error handling
- Include `setErrorHandler` as a package export
- Add/update unit testing for affected modules
Notes:
- Updated functions that returns a promise to reject said promise on cases where the request failed.
- Improved how we test promise resolving/rejection.
> CMP restructure phase 6

- src/store.test.ts
- src/store.ts
Currently we trigger the `onStateChange` callbacks every time the state is set through `setConsentState()`. However the state being set might be the same as the current, in which case there's no use triggering the `onStateChange` callbacks. This is what this PR changes.
> Call state change handlers only when consent is not the same

- src/store.ts
...so it acts as expected while we're not using these purposes.
> Comment out PECR logic in stateChanged()

- src/component/ConsentPreferencesDashboard.tsx
...as it was using the wrong one and making the script pass all Nulls when the user clicked 'Enable all and continue'
> Fix parameter used when calling setConsentState

- package.json
- rollup.config.js
- tsconfig.json
- yarn.lock
We currently have 2 separate build processes:
- One to build the CMP system that uses tsc
- One to build the CMP UI that uses rollup to bundle.
Besides being bad practice to have two separate build processes this is causing unwanted effects where 2 different instances of `store.ts` are created as opposed to only one that is shared between the core and the ui parts of the library.
We want to avoid importing the UI components unless the UI needs to be shown, which means having 2 bundles (one for the system and one for UI). These two bundles should use the same instance of the `store.ts` code (or whatever it transpiles to).
This PR makes changes so only a single build process exists. The new process uses rollup to create 2 bundles. As a side effect a common bundle is created that contains …
> Unified build process

- package.json
- src/store.test.ts
- src/store.ts
This PR has 2 changes:
1. Temporarily `getVendorList` will use IAB vendor list endpoint instead of our own internal end point whilst we resolve caching issues.
2. Only fetch the vendorList when it's required. Previously we were always fetching the vendor list from `store.init`, even if `store.getVendorList` was never called. this was an enhancement to ensure the vendor list was available as early as possible, but in reality it means we're making many unnecessary request for the vendor list.
> update getVendorList to use IAB vendor list endpoint

- package.json
- src/component/ConsentManagementPlatform.tsx
This PR re-introduces the `whatwg-fetch` dependency into the `CMP` component - this is required for older browsers that don't support `window.fetch` (eg. IE11)
> Polyfill fetch

- README.md
- package.json
- src/cmp-ui.test.ts
- src/cmp-ui.ts
- src/cookies.test.ts
- src/cookies.ts
- src/store.test.ts
- src/store.ts
ShouldShow now differentiates between re-permissiong  and non re-permissioning conditions to allow frontend to have a test running at with one behaviour and roll out to rest of the audience with the other. Updated unit tests and documentation to reflect changes.
Also removed logic related to saving legacy cookie.
> ShouldShow repermissioning code

- src/cookies.test.ts
- src/cookies.ts
Fixes a bug where cookies were not being saved when accessing viewer.gutools.co.uk.
This was happening because we never accounted for domains using a second level domain such as `viewer.gutools.co.uk`. So when slicing the full domain to remove subdomains we were getting `.co.uk` and setting it as the cookie domain, which the browser ignored.
> Fix cookies not saving in viewer.gutools.co.uk

- src/component/Modal.tsx
There is an accessibility issue on the modal for users without a scroll wheel. Users would have to click somewhere in the modal before being able to use the arrows keys to scroll. This PR forces the browser to focus on scrollable element of the modal immediately allowing the user to scroll the modal and also using tab to navigate it.
> Fixes scrolling accessibility issue

- package.json
- src/component/CmpCollapsible.tsx
- src/component/Modal.tsx
On iOS 10 devices (iPhone or iPad) the modal in the CMP UI is not entirely scrollable, users report being unable to scroll to the "Measurement" on/off radio buttons and the "Vendors" and "Features" lists without the scroll bouncing back to it's original position. I can verify this bug was reproducible on Browserstack.
The issue was caused by the "scrollable" div not rendering at the expected height, this PR fixes that by using a different technique to set the height of this element. 
This has been tested non Browserstack against a range of devices/browsers on desktop/mobile/tablet.
**Bug on iOS 10 iPhone...**
**Fixed on iOS 10 iPhone...**
Trello card: https://trello.com/c/iDngBtE8/646-cmp-investigate-cmp-ios-1033-issues
> Fix iOS 10 modal scrollable bug

- package.json
- src/component/Banner.tsx
- src/component/CmpCollapsible.tsx
- src/component/CollapseItemButton.tsx
- src/component/Modal.tsx
- src/component/OnOffRadio.tsx
Whilst integrating the CMP UI component into `dotcom-rendering` we found styles were applied compared to `frontend`, this is because `frontend` uses a different set of default css styles compared to `dotcom-rendering`. To overcome this problem we've had to explicitly declare style rules  where we'd previously implicitly inherited them from `frontend`'s defaults. This creates a pixel accurate version of the CMP UI across both versions of the site.
> Pixel Parity between frontend and dotcom-rendering

- package.json
- src/component/Banner.tsx
- yarn.lock
Any user using keyboard navigation who loads the Guardian and sees the CMP UI has to tab through the entire page to reach it. Following the change to `@guardian/src-button` here https://github.com/guardian/source/pull/216/files we can now add the `tabIndex` attribute to our `<Button>` components, which means the CMP UI now becomes the first item the tab index moves to from the toolbar.
> Accessibility update - add tabIndex

- .eslintrc.json
- package.json
- src/component/Modal.tsx
This PR reveals the scrollbar on the scrollable area of the `Modal` component. We had removed the scrollbar from the CMP UI back when it was a side banner to avoid having 2 scrollbars. When we moved to a bottom banner + modal UI we never revisited that decision but recent accessibility issues have caused us to rethink it. We have decided to reinstate it.
**Before:**
**After:**
> Show scrollbar in modal

- package.json
- rollup.config.js
- src/component/Banner.tsx
- src/component/CmpCollapsible.tsx
- src/component/CollapseItemButton.tsx
- src/component/Modal.tsx
- yarn.lock
The Dotcom team identified that the CMP Component when bundled is bringing its own versions of `src-foundations`, `src-button` and `src-svgs` dependencies. These are already being bundled by DCR and other dependent packages
Since CMP is designed to be consumed by other applications,  these modules should be externalised, and specified as `peerDependencies`, rather than bundled with the CMP Component.
This PR does that by enacting the following changes:
- externalise src-* packages in the rollup config
- specify scr-* packages as peerDependencies rather than dependencies 
- Upgrade src-* packages to the latest version (0.16.1)
- `src-foundations@0.16.1` now exports `headlineSizes`/`bodySizes` as `px` values and not `rem` values, so this required an update to some styles.
After running a …
> Move src-* dependencies into peerDependencies

- package.json
- src/component/Banner.tsx
- src/component/CmpCollapsible.tsx
- src/component/CmpListItem.tsx
- src/component/ConsentManagementPlatform.tsx
- src/component/Modal.tsx
- src/component/Vendors.tsx
- src/component/utils/config.ts
This PR updates the copy on the banner and the behaviour when clicking the 'partners' link/button so address compliancy issues reported by the IAB.
When clicking the 'partners' link it will now open the modal with the Vendors section expanded and scroll to it, making it visible for the user.
Screenshot showing the updated copy:
Also took the opportunity to remove some unused config variables.
> IAB compliancy update

- package.json
- src/component/Banner.tsx
Fixes a small typo in the copy of the banner.
> Fix a typo in the copy

- package.json
- src/component/Banner.tsx
This PR removes the AB test for testing copy introduced in PRs https://github.com/guardian/consent-management-platform/pull/75 and https://github.com/guardian/consent-management-platform/pull/78 making the variant the standard version.
> Remove copy AB test

- src/sourcepoint.ts
Successfully implements the first test of the Sourcepoint implementation (introduced unsuccessfully in https://github.com/guardian/consent-management-platform/pull/83).
We got the confirmation from Sourcepoint that the `mssDomain` property should not include the account ID.
Because we are running it this test localhost we needed to add the `propertyHref` to mask the request and make it seem like it's coming form a guardian subdomain.
> Sourcepoint test TCF v2 integratioon

- package.json
- yarn.lock
Remove our pre-push hooks and the husky dependency that we were using for it.
We have git actions to validate our code now, so this is no longer necessary. Developers can still validate their code locally by running `yarn validate`
> Remove husky lib and hooks

- dev/app.tsx
- src/ccpa/core.ts
- src/ccpa/sourcepoint.ts
- src/index.test.js
- src/index.ts
Adds `checkWillShowUI` to API that will return the promise of a boolean. This boolean can be used to determine if a CCPA message will be shown on the current pageload.
> Add checkWillShowUI to API

- src/ccpa/sourcepoint.ts
As per the [sourcepoint documentation](https://documentation.sourcepoint.com/web-implementation/sourcepoint-setup-and-ccpa-configuration), which updates the `mmsdomain` to point at `consent.theguardian.com` which has been set up for this purpose.
> Set mmsdomain to consent.theguardian.com

- .editorconfig
- .prettierrc
- README.md
This PR presents a suggested API for CMP v4 in README.md form. v4 of the CMP will replace our TCF v1 implementation with Sourcepoint's TCF v2 implementation.
> Define CMP v4 API

- src/ccpa/sourcepoint-stub.js
- src/ccpa/sourcepoint.test.js
- src/ccpa/sourcepoint.ts
Only adds CCPA stub from Sourcepoint when CCPA is actually in use.
Reintroduces the code from #109 and puts the script element creation inside a function.
> Stop CCPA stub being added to every page

- src/ccpa/sourcepoint.ts
- src/tcfv2/sourcepoint.ts
- src/types.d.ts
`onConsentChange` callbacks are also now invoked after the user dismisses banners that sourcepoint doesn't think of as setting consent (e.g. CCPA).
fixes https://trello.com/c/5XgaVhHG
> handle some messages not setting consent when dismissed

- .babelrc.js
- package.json
- rollup.config.js
- src/index.test.js
- src/index.ts
- src/tcfv2/sourcepoint.ts
- src/tcfv2/stub.js
- tsconfig.build.json
- tsconfig.json
- yarn.lock
- installs old CMP with `@guardian` scope
- stops trying to build the old CMP
- adds an ES module version to the package
- removes the IAB tcf stub for the sourcepoint one (hopefully less likely to get bitten)
- cleans up `package.json`
> fix and update TCFv2 build

- src/onConsentChange.test.js
- src/onConsentChange.ts
- src/tcfv2/sourcepoint.test.js
This adds tests for `onConsentChange`. Test coverage is 100% thanks to `/* istanbul ignore else */`. See syntax on [BestofJS](https://bestofjs.org/projects/istanbul#Parsing%20Hints)
We can mock the `window.__uspapi` and test our work.
> TCFv2 onConsentChange tests

- src/index.ts
- src/oldCmp.ts
- src/onConsentChange.test.js
- src/onConsentChange.ts
- src/tcfv2/sourcepoint.test.js
While the AB test is running, we will still need to expose the old CMP's `init()` for users in the USA.
The three 3, mutually-exclusive groups—thanks @ripecosta for clarifying—that a user might fall in are:
1. In USA: old CCPA _(requires `init({ccpaApplies: true})`)_
2. In RotW: old TCFv1 _(no `init()` required)_
3. In RotW (1%): new TCFv2 _(new `init({isInUsa: false})`)_
The old CMP's init is required for **Group 1**, and this PR aims to fix that. 
The TCFv2 AB test will run smoothly. 
In frontend, the CMP will then be called through [`guardian/frontend/…/javascripts/boot.js#36`](https://github.com/guardian/frontend/blob/193bc01c52fe773d449d86604feba027e29ab6e2/static/src/javascripts/boot.js#L36)  :
```js
// Start CMP
if (isCcpaApplicable()) {
oldCmp.init({ useCcpa: true });
} else if …
```
> TCFv2 expose old CCPA init()

- .gitignore
- src/index.ts
The `InitOptions` interface needs to be exported for the V4.0.0 to work. Otherwise we get the following error.
```bash
src/oldCmp.ts:9:14 - error TS4023: Exported variable 'oldCmp' has or is using
name 'InitOptions' from external module "@guardian/old-cmp/dist/index"
but cannot be named.
```
Old and new CMP can work together.
> Types export for old CMP

- package.json
- src/oldCmp.ts
- yarn.lock
- The old CMP now expose the `InitOptions` interface in v3.4.9, otherwise publishing the v4 packages does not work.
- The new CMP exposes `oldCmp.checkWillShowUi`
Force-pushing to TCFv2, so this PR now contains commit 7519f85a94ec5c76a634c21e1a635a52dbd17da4
The v4 package can be released to NPM.
> Bump old CMP to 3.4.9

- package.json
- src/oldCmp.ts
- src/tcfv2/stub.js
We are implementing the IAB stub from SourcePoint in a non-standard manner, and this fixes an error:
```log
index.esm.js:324 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
at stub (index.esm.js:324)
at init (index.esm.js:333)
at Object.init (index.esm.js:380)
at Object.init$4 [as init] (index.esm.js:417)
at boot.js:40
at wrapped (raven.js:347)
```
Frontend now works.
> Fix stub for our implementation

- package.json
- src/ccpa/index.ts
- src/ccpa/sourcepoint.test.js
- src/ccpa/sourcepoint.ts
- src/lib/accountId.ts
- src/lib/sourcepointConfig.ts
- src/tcfv2/index.ts
- src/tcfv2/sourcepoint.test.js
- src/tcfv2/sourcepoint.ts
Update Sourcepoint ID so they pointing to the right privacy managers and vendor lists.
On PROD / CODE, a place in the US should be able to see the privacy manager when clicking "Do Not Sell My Data"
We should be able to see the privacy manager in CCPA (US).
Yes: Sourcepoint needs to work!
n/a
> TCFv2 fix Sourcepoint IDs

- src/onConsentChange.test.js
- src/onConsentChange.ts
This PR returns a consistent `TCData.purpose.consents` object, where all purposes (1 to 10) are set to a boolean.
The native IAB implementation would return an empty object `{}` in case all purposes are false. This is due to their implementation using a [Boolean Vector]. In practice, this would mean that previously:
- consented purposes: `[]` -> consent object: `{}`
- consented purposes: `[2]` -> consent object: `{ '1': false, '2': true }`
- consented purposes: `[2,5]` -> consent object: `{'1': false, '2':true, '3': false, '4': false, '5': true }`
The new behaviour is now more explicit:
- consented purposes: `[]` -> consent object: `{'1': false, '2': false, '3': false, … , '9': false, '10': false}`
- consented purposes: `[2]` -> consent object: `{ '1': false, '2': true, '3': false, … , …
> TCFv2 return all states

- package.json
- src/onConsentChange.ts
Fix a bug in the shape of the `state` object. `vendorConsents` is now returning proper `key: value` pairs.
Print the state object, it should look like this:
```js
{
consents: {
1: Boolean,
2: Boolean,
// etc.
},
eventStatus: String, // 'tcloaded' | 'cmpuishown' | 'useractioncomplete'
vendorConsents: {
'abcdefghijklmnopqrstuvwx': Boolean,
'yz1234567890abcdefghijkl': Boolean,
'mnopqrstuvwxyz1234567890': Boolean,
// Sourcpoint IDs, etc.
}
}
```
Non-consented vendors should be prevented from running.
n/a
n/a
> TCFv2 fix vendor grant

- README.md
Follow up on #190, making the returned `tcfv2.consents` explicit in the [README.md][].
[README.md]: https://github.com/guardian/consent-management-platform/blob/tcfv2-return-all-states/README.md
More explicit README
> TCFv2 Update README

- README.md
- src/ccpa/index.ts
- src/ccpa/sourcepoint.test.js
- src/ccpa/sourcepoint.ts
- src/index.ts
- src/tcfv2/index.ts
- src/tcfv2/sourcepoint.test.js
- src/tcfv2/sourcepoint.ts
- src/types.d.ts
This adds a pubData type to the `window._sp_.config` type and also updates the `init` function so that we can pass along data to be used by SourcePoint. This will allow us on web to associate the current `browserId` with an impression/consent signal from the CMP.
The `pubData` is a free field where we can add anything; it will show up in the data that SourcePoint then send to us.
@guardian/commercial-dev
> Add pubData to SourcePoint config object

- src/types.d.ts
Minor change to reuse the `PubData` type within the TCF `_sp_` object.
@guardian/commercial-dev @mxdvl
> Reuse PubData type

- src/index.ts
- src/types.ts
makes sure `willShowPrivacyMessage` will resolve a boolean even if CMP has failed to mount
> willShowPrivacyMessage should never resolve undefined

- dev/app.tsx
- src/ccpa/sourcepoint.test.js
- src/ccpa/sourcepoint.ts
- src/onConsentChange.ts
- src/window.d.ts
After good sleuthing by @jeteve, we noticed that if `onConsentChange` is called _while_ `cmp.init` is being run, callbacks that have already been added may never be invoked 😱…
- use a per-callback state comparison, rather than a global one
- moves the first `invokeCallbacks` for CCPA to immediately after the `uspapi` is available
> Fix (hopefully) ads in USA

- .eslintrc.json
- README.md
- package.json
- rollup.config.js
- src/index.test.js
- src/index.ts
- src/oldCmp.ts
- yarn.lock
adds `oldCmp` back so we can proceed with improvements to CMP while working out how to remove old cmp from dotcom
cc @ripecosta – back from the grave!
> Restore old CMP

- README.md
- src/disable.test.js
- src/disable.ts
- src/index.ts
Adds helper exports to disable the CMP entirely in the current browser – other teams need this in their tests:
- `cmp.__enable()`
- `cmp.__disable()`
- `cmp.__isDisabled()`
The same can be achieved manually by setting/removing a cookie:
- `gu-cmp-disabled=true` 
cc @paulmr @rtyley @gtrufitt @coldlink
> Make CMP disableable and enableable

- README.md
Makes the README a little shorter.
> ReadMe: use toggle for vendor IDs

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/CI.yml
- .github/workflows/PR.yml
- .releaserc.json
- docs/01-development-instructions.md
- package.json
- yarn.lock
- adds semantic release pipeline steps to CI workflow, along lines of https://github.com/guardian/commercial-core
- updates CI steps to manually pull node version out of `.nvmrc`, because [`nvm install` doesn’t actually change the node version for following steps](https://github.com/guardian/commercial-core/runs/1258855238?check_suite_focus=true#step:5:6) in github actions
> build: add semantic release

- src/types/countries.ts
uses object type for countries
so we can get a union type of the value for input
> fix: use object type rather than enum to store countries

- README.md
This should probably trigger a release, even though it’s only `docs`.
There is a lack of details on the shape of the `consentState.aus` object
> fix: update README on `consentState.aus`

- src/types/countries.ts
- allows `string` types for country
- DCR `countryCode` type is string, so this is a quick fix for Aus release
- we could pull [the geo stuff out of DCR](https://github.com/guardian/dotcom-rendering/blob/main/src/web/lib/getCountryCode.ts) into https://github.com/guardian/libs and set the correct ISO type in there (cc @gtrufitt @liywjl)
- we could then revert this PR
- that also opens up the possibility of not needing to pass location in, we can use the lib ourselves
> fix: accept `string` as a country (for now)

- src/getConsentFor.test.js
- src/getConsentFor.ts
The `getConsentFor` method did not support the AUS framework.
This needed to be updated before it could be used in production.
It might be worth changing the shape of the AUS consent state to make it easier to handle.
> fix: add AUS getConsentFor

- README.md
- src/index.test.js
- src/index.ts
Allow calling the API with `cmp.init({ isInUsa })`.
Because we can never fully synchronise releases in DCR & frontend, we always need to support old API interfaces.
> feat: AUS handle old API params

- src/index.ts
- src/types/index.ts
- src/types/window.d.ts
restores old types to init interface
missed in #322
> fix: add new types back to window object

- src/aus/sourcepoint.ts
Changes the name of variable `ccpaLib` to `ausLib` in AUS.
Clearer.
> refactor: Fix variable name

- .releaserc.json
enables `beta` releases by merging to the new [`beta`](https://github.com/guardian/consent-management-platform/tree/beta) branch instead of `main`
https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#pre-release-branches
enables us to test pre-release versions
> chore: enable beta releases via semantic release

- cypress/integration/sourcepoint-ccpa.spec.js
- cypress/integration/sourcepoint-tcfv2.spec.js
- src/getConsentFor.test.js
- src/getConsentFor.ts
In AUS, Instead of testing agains specific custom vendors, check for the “Advertising” category.
This decision has been clarified as being the expected behaviour.
> fix: only test against advertising category

- cypress/integration/sourcepoint-ccpa.spec.js
- cypress/integration/sourcepoint-tcfv2.spec.js
- cypress/utils.js
- src/aus/api.test.js
- src/aus/api.ts
- src/aus/sourcepoint.ts
- src/onConsentChange.test.js
- src/rollup.config.js
delays calls to `uspapi` until the sourcepoint library has loaded in aus
sourcepoint's custom `'getCustomVendorRejects'` extension to `__uspapi` doesn't implement the queue that the standard `__uspapi` options are required to. 
they suggested the following:
> wait until we have determined the siteID before calling __uspapi('getCustomVendorRejects');
this is an attempt but it doesn't seem to work...
> fix: wait for sourcepoint library to load in aus

- src/aus/api.test.js
- src/aus/api.ts
- src/aus/sourcepoint.ts
- src/ccpa/api.ts
- src/onConsentChange.test.js
- src/tcfv2/api.ts
More robust checks for when SP library has loaded. Any callback events now triggers the `getCustomVendorRejects` call. Follow-up on #354. 
- Renamed promise to `sourcepointLibraryLoaded`
`onConsentReady` does not fire when a user gets the banner show and clicks “Continue”. Using the `willShowPrivacyMessage` is more robust, and always fires once the SP library is loaded.
> fix: await __uspapi

- README.md
- src/aus/__fixtures__/api.getUSPData.json
- src/aus/api.test.js
- src/aus/api.ts
- src/aus/getConsentState.test.js
- src/aus/getConsentState.ts
- src/getConsentFor.test.js
- src/getConsentFor.ts
- src/onConsentChange.test.js
- src/types/aus.ts
- src/types/index.ts
Just rely on good old `getUSPData` in AUS.
We're not using the granularity of `getCustomVendorRejects`, and it's a half-baked solution that causes a plethora of errors everywhere.
> fix: use CCPA getUSPData API in AUS

- README.md
Does 3 small corrections to the README. 
- `Expected parameters` was next to `options.isInUsa` instead of next to `options.pubData`, which didn't seem like the right place given the example below it.
- Docs stated that `consentState.tcfv2` would be undefined if user was outside the US or Australia when it's the other way around.
- Typo in a comment fixed while I was in the area.
> docs: Small corrections to README

- package.json
- src/getCurrentFramework.ts
- src/index.ts
- src/lib/mark.ts
- test-page/App.svelte
- yarn.lock
Uses the new and shiny `log` from `@guardian/libs`.
We can log more to the console, without polluting.
> feat: use @guardian/libs logger

- src/aus/sourcepoint.ts
- src/ccpa/sourcepoint.ts
- src/tcfv2/sourcepoint.ts
Returns a state with no consent as soon as possible, before a new user interacts with the banner.
We don’t need to wait for SP events. Closing #382
> fix: Invoke callbacks instantly in TCFv2

- src/index.test.js
Fix tests that were marked as `todo` or skipped.
- [stop skipping `cmp.willShowPrivacyMessage()`](https://github.com/guardian/consent-management-platform/pull/389/files#diff-38a2b85ac1b61b44eb1945e128241cb5ef01e5646cf06b586f5c0114b153fa0eL114), introduced in #263
- Actually tests [this](https://github.com/guardian/consent-management-platform/commit/3de44275d93348d34fc66cb704d25b0cf0286c29) from 3de44275
Better coverage, better testing, better code health.
> test: Maintenance

- src/tcfv2/getConsentState.ts
Adds error when tcdata are empty 
to help debug sentry longs 
https://trello.com/c/1JjoL8jq/1254-investigate-consent-error-logs
> feat: Add error when tcdata are empty

- src/types/index.ts
Attempt to fix the below error when importing latest version to DCR which uses typescript:
```
node_modules/@guardian/consent-management-platform/dist/types/index.d.ts:12:21 - error TS2304: Cannot find name '__PACKAGE_VERSION__'.
12     version: typeof __PACKAGE_VERSION__;
```
It should allow updating latest cmp version to DCR
> fix: change type of version to string

- src/tcfv2/getConsentState.ts
Switch debug console to throwing a new Error when tcdata is empty
Hopefully this would get picked up by Sentry
> fix: Switch debug console to new Error

- .github/workflows/CI.yml
- .github/workflows/gh-pages.yml
uses guardian/actions-setup-node
cleaner
> chore: use guardian/actions-setup-node

- src/ccpa/sourcepoint.ts
- src/tcfv2/sourcepoint.ts
- src/tcfv2/stub.js
`onConsentReady` is when consent is really ready. We used `onMessageChoiceSelect`, but it’s not as reliable.
Shortly, we should simply add an event listener to the `__tcfapi`.
New visits did not get a consented state and end-to-end tests are failing.
> fix: Trigger callbacks when consent is ready

- cypress/integration/sourcepoint-tcfv2.spec.js
- package.json
- yarn.lock
Enables TCFv2 testing in continuous integration workflow.
Sourcepoint now runs all frameworks globally, and it is the CMP’s job to make the right call on which framework to run. These tests were failing for a while, and it looks like #431 fixed them.
> chore(tests): Run TCFv2 in CI workflow

- cypress/integration/sourcepoint-aus.spec.js
- cypress/integration/sourcepoint-ccpa.spec.js
- test-page/App.svelte
Co-Authored-By: Max Duval <max.duval@theguardian.com>
This adds end-to-end tests for Australia.
They didn't exist before. We now have global geolocation enabled.
> test: add end-to-end tests for aus

- src/tcfv2/getConsentState.ts
This error wasn't pick up before
gu.geolocation will become obsolete
> fix: remove getting country code

- .vscode/extensions.json
- .vscode/settings.json
- README.md
- src/aus/getConsentState.ts
- src/aus/sourcepoint.ts
- src/ccpa/getConsentState.ts
- src/getConsentFor.test.js
- src/getFramework.test.js
Adds a spell checker extension. Sets a few IAB and consent-specific keywords to the dictionary:
- Sourcepoint
- ccpa
- tcfv (the 2 is ignored)
- tcfapi
- uspapi 
- _etc._
We all have MacBooks with butterfly keyboards.
> style: Add code spell checker extension

- package.json
It’s used in the code, and therefore is a regular dependency.
Peer dependency is the wrong concept, and makes consumer applications (i.e. `frontend`) complain if we use v2 of the libs.
> fix: make `@guardian/libs` a regular dependency

- .github/workflows/PR.yml
Forces single commits to be worded properly, because squash and merge does not use the PR title if you have only one commit.
Whoops #467
Enabled in https://github.com/guardian/commercial-core/pull/191
> fix: validate single commits

- .husky/pre-push
- README.md
- cypress/support/commands.js
- package.json
- src/types/tcfv2/CustomVendorConsents.ts
- yarn.lock
Upgrades dependencies
- Cypress
- Husky https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7
- plugin-commonjs
- @babel/core
- start-server-and-test
> chore: Bump deps 2021.08.17

- README.md
- src/index.test.js
- src/index.ts
- src/types/index.ts
Remove deprecated paramter `isInUsa` from paramters of `cmp.init`
The parameter has been deprecated in favour of `country`
> feat!: Remove deprecated parameter `isInUsa`

- .releaserc.json
- package.json
- yarn.lock
Add dependency [conventional-changelog-conventionalcommits](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits) and add preset conventionalcommits to `.releaserc`
This allows the use inclusion of `!` in commit messages to trigger major releases.
> chore!: conventional commit preset

- src/onConsentChange.test.js
- src/onConsentChange.ts
Wait for user action to trigger callbacks in TCFv2. If `eventStatus` is `'cmpuishown'`, don’t trigger the callbacks.
Otherwise, we always get a state similar to “Reject All” as the first state, very shortly followed by the actual one chosen by the user.
> fix: Wait for user action to trigger callbacks in TCFv2

- src/getConsentFor.ts
- src/types/index.ts
- Export type `VendorName`, an enum of the vendors supported by the CMP (`'a9' | 'acast' | 'braze' `, etc.)
`VendorName` needs to be imported by consumers of `getConsentFor` so that they can be converted to TypeScript.
> feat: Define and export type `VendorName`

- src/getConsentFor.ts
We’ve now switched to the official Prebid vendor ID.
We can’t check for Prebid consent otherwise.
> fix: Prebid uses IAB vendor ID

- src/index.ts
- src/lib/domain.ts
This PR attempts to make initialising the CMP in a server environment (where there is no `window`) safe to do.
From the suggestion in to https://github.com/guardian/dotcom-rendering/pull/3925
> feat: Make initialising the CMP server-safe

- src/getConsentFor.ts
- src/index.ts
- src/lib/domain.ts
- src/onConsentChange.ts
- src/server.ts
- src/types/index.ts
Incorporate changes from https://github.com/guardian/dotcom-rendering/pull/4106
This change makes it clear the CMP is not to be used server-side and warns in console to that effect.
> fix: Simplify server side implementation

- .github/workflows/CI.yml
- .github/workflows/PR.yml
- .github/workflows/gh-pages.yml
- package.json
- yarn.lock
This change combines all outstanding Dependabot PRs as of 7/3/22 into one PR for release.
Stay secure, stay up-to-date.
> chore: Dependabot cherry-pick PR

- src/vendors.ts
This change adds `linkedin` to the list of vendors so that a call to `getConsentFor` can reference this vendor when checking for consent.
The Sourcepoint vendor ID mapping is [retrieved from their API](https://sourcepoint.mgr.consensu.org/tcfv2/vendor-list?vendorListId=5ec67f5bb8e05c4a1160fda1).
This is required for to allow the marketing team responsible for Membership events to add LinkedIn's Insight tracking pixel and have this be added to the page _only_ when consent has been given.
> feat: Adds linkedin to list of vendors

- README.md
- src/getConsentFor.ts
- src/onConsentChange.ts
- src/tcfv2/stub.js
- src/types/tcfv2/TCData.ts
- src/types/tcfv2/index.ts
Co-authored-by: Max Duval <max.duval@theguardian.com>
Replace git.io links with resolved links as git.io will be deprecated on 2022-04-29:
https://github.blog/changelog/2022-04-25-git-io-deprecation
Used @mxdvl 's guide
> chore: Replace git.io links with resolved links

- artifact.json
- cdk/bin/cdk.ts
- monitoring/remoteRun.ts
- monitoring/src/config.ts
- riff-raff.yaml
This change adds monitoring lambdas to the `ca-central-1` region.
The advertising setup in Canada is different from elsewhere and has had unusual / different behaviour with the CMP in the past. This change will allow us to test in this region.
**Note**: When this is deployed we will need to follow the instructions in https://github.com/guardian/consent-management-platform/blob/main/riff-raff.yaml#L6 as this will add a new stack.
> test: Add Monitoring Lambdas for Canada

- monitoring/src/index.ts
- monitoring/src/types.ts
Move towards better reporting on failure.
At the moment the lambda monitoring only returns logs, this adds a return status (so far unused).
> test: Express failure in types

- cdk/lib/__snapshots__/monitoring.test.ts.snap
- cdk/lib/monitoring.ts
Increase the memory allocation of lambda as it is hitting the limit sometimes.
Reduce false reporting of errors when lambda stalls as it runs out of memory.
> test: Increases memory allocation of lambda to 2048

- monitoring/src/check-page/aus.ts
- monitoring/src/check-page/ccpa.ts
This is an addition to https://github.com/guardian/consent-management-platform/pull/620 to add `browser.close()` instruction in the ccpa and aus cases.
> test: add missing instuctions in the ccpa and aus checkPages functions

- src/vendors.ts
Adds Quantum Metric as a vendor identifiable to the `getConsentFor` function as `qm`.
Example use: 
```ts
const qmConsent: boolean = getConsentFor('qm');
```
Needed for https://trello.com/c/72Khgq68/709-add-quantum-metric-to-list-of-vendors-the-cmp-knows-about (requested by @GHaberis).
> fix: Update getConsentFor to include Quantum Metric

- .github/workflows/gh-pages.yml
The current version of the `ghpages` action is hard coded [to publish from `master`](https://github.com/maxheld83/ghpages/blob/master/entrypoint.sh#L16) whereas we use `main`.
This updates to use a forked version of the action [that references `main`](https://github.com/guardian/ghpages/blob/master/entrypoint.sh#L16). This approach was taken as the original repo seems abandoned with an outstanding [issue to fix the issue open for over a year](https://github.com/maxheld83/ghpages/issues/35).
So that our build works and publishes to gh-pages.
> docs: Use update ghpages action

- .github/workflows/snyk-pr.yml
The paths param in the GitHub action should specify package.json at any depth (as there are multiple in this repo).
This will ensure we see changes in all projects in this repo.
> test: Update Snyk PR to cover **/package.json

- .github/workflows/CI-monitoring.yml
- .github/workflows/CI.yml
- .github/workflows/gh-pages.yml
This repository currently uses both `guardian/actions-setup-node` and `actions/setup-node`.
`guardian/actions-setup-node` is a fork of `actions/setup-node` and has fallen behind. In this change, we move to using only `actions/setup-node` for simplicity.
Also replace `bahmutov/npm-install` with a DIY solution, as it's not too complex and removes a dependency: we use `actions/setup-node` to manage the cache, and manually install yarn deps.
> ci: Use `actions/setup-node` to remove a dependency

- .vscode/settings.json
- artifact.json
- cdk/bin/cdk.ts
- cdk/lib/__snapshots__/monitoring.test.ts.snap
- cdk/lib/monitoring.test.ts
- cdk/package.json
- cdk/yarn.lock
- project/build.properties
- riff-raff.yaml
Updates Gucdk version to 39.0.0 - successfully tested in code.
As per the issue raised [here](https://github.com/guardian/consent-management-platform/issues/645) -  using the latest version is always desired, and this'll enable us to test a feature from the cdk.
> chore(deps): bumped gucdk to v39

- cdk/bin/cdk.ts
- cdk/cdk.json
- cdk/lib/monitoring.test.ts
- cdk/lib/monitoring.ts
- cdk/package.json
- cdk/yarn.lock
Updates Gucdk version to 41.0.0
As per the issue raised https://github.com/guardian/consent-management-platform/issues/645 - using the latest version is always desired, and this'll enable us to test a feature from the cdk.
> chore(deps): bump gucdk to v41

- cdk/bin/cdk.ts
- cdk/lib/monitoring.test.ts
- riff-raff.yaml
Generate new stacks based on lists of region & env.
Removes a bit of code duplication, makes adding removing regions a bit more straightforward.
note: this will rename the Asia Pacific region stack (replacing AU with AP)
> refactor: generate stacks from list of envs and regions

- cdk/package.json
- cdk/yarn.lock
Updates Gucdk version to 47.0.0
As per the issue raised https://github.com/guardian/consent-management-platform/issues/645 - using the latest version is always desired, and this'll enable us to test a feature from the cdk.
co-authored-by:  @Georges-GNM
> chore(deps): bump gucdk to v47

- cdk/bin/cdk.ts
- riff-raff.yaml
This change updates the stack name in the CDK package to make it clear who owns these lambdas in reporting.
It's wrong now.
**Note:** This needs a change to riff-raff configuration to understand that the `cmp-monitoring` stack needs deploying into the Frontend account.
> chore: Update stack name to disambiguate stack 

- package.json
- yarn.lock
Updates to the latest version of guardian/lib
To keep up to date.
> fix: bump version of guardian/lib

- package.json
- yarn.lock
Updates to the latest version of guardian.libs.
Keep up to date.
> fix: bump guardian.lib to 7.1.4

- monitoring/src/check-page/aus.ts
- monitoring/src/check-page/ccpa.ts
- monitoring/src/check-page/tcfv2.ts
Alters the monitoring test to use class names to identify the buttons within Sourcepoint's CMP in the absence of HTML element ids.  
This fixes the issue that ab tests often change the text of the button which we were previously relying on.  It makes the monitoring tests slightly less fragile until we can persuade Sourcepoint to add ids into their code. (we hope).
Sue Burt and Akinsola Lawanson
> refactor: Moving from using title text to using apparently-unique class names to identify SourcePoint buttons

- riff-raff.yaml
During a CloudFormation deployment, Riff-Raff sets the stack policy to protect against unintentional deletion of sensitive resources (see https://github.com/guardian/riff-raff/pull/623). The policy it uses is the same regardless of region. However, when the policy is applied to the us-west-1 region, we get an error.
We previously set `manageStackPolicy` to `false` to opt-out of this behaviour, as deployments to us-west-1 would otherwise be impossible.
https://github.com/guardian/riff-raff/pull/874 patches Riff-Raff to make the policy region aware, removing the need for this workaround.
- More standard deployment configuration
- More protection during deployment
- Unblocks https://github.com/guardian/consent-management-platform/pull/659
To be merged after …
> ci: Remove Riff-Raff configuration workaround

- cdk/lib/__snapshots__/monitoring.test.ts.snap
- cdk/package.json
- cdk/yarn.lock
Also updates `aws-cdk`, `aws-cdk-lib`, and `constructs` to match:
```console
➜ npm info @guardian/cdk@48.0.1 peerDependencies
{
'aws-cdk': '2.45.0',
'aws-cdk-lib': '2.45.0',
constructs: '10.1.127'
}
```
- Keeping up to date
- A prerequisite to #659
- [Successfully deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/c343ab75-a40f-4bff-9951-d872142ae4cf)
> chore(deps): Update @guardian/cdk to v48.0.1

- package.json
- src/rollup.config.js
- yarn.lock
- makes `@guardian/libs` a peer dependency
- adds a pinned `@guardian/libs` to dev dependencies (per [the recommendation](https://github.com/guardian/recommendations/blob/main/npm-packages.md#pin-the-lowest-possible-version-of-peerdependencies-in-your-packages-devdependencies))
- bumps the version of `@guardian/libs` it uses
currently the CMP bundles libs with CMP code. this means it ships two copies to browsers. changing it to a peer dep means consumer's handle the presence of libs.
co-authored @joecowton1
> refactor!: make `@guardian/libs` a peer dep

- docs/02-sourcepoint-ui-instructions.md
- sourcepoint-ui/README.md
- sourcepoint-ui/live/TCFv2/theguardianDotCom TCFv2 first_layer.css
Minor change to update the CSS stub for TCFv2 in DotCom to the latest version which includes the tab index focus changes.
Also update to the docs in relation to making changes to the CSS in Sourcepoint's portal and being able to test locally.
To keep an up-to-date versioned copy of the current CSS file associated with our live Sourcepoint banner.
> refactor: update the css stub for tcfv2 dotcom plus documentation

- monitoring/src/check-page/common-functions.ts
- monitoring/src/check-page/tcfv2.ts
- monitoring/src/types.ts
This captures the version of the CMP each time it runs Monitoring in order to allow us to gain better visibility over exactly when Sourcepoint upgrades it's CMP.
This aids our debugging - ruling in or out a potential change in the background over which we have little control.
This will appear in the logs each time monitoring runs.
Occasionally in the past, such an upgrade has impacted the service and it has been difficult to know whether or not it was on our supplier's end or ours.  Our supplier only gives us a time range of a week when they plan to do an upgrade so this will provide us with greater accuracy.
> test: Capture the CMP version when our supplier upgrades the CMP

- jest.config.js
- package.json
- yarn.lock
Upgrades to Jest and Cypress to next major version to remove transitive dependency on jsprim@1.4.1
jest@26.6.3 requires json-schema@0.2.3 via a transitive dependency on jsprim@1.4.1 
This upgrade ensures jsprim@2.0.2 and removes json-schema@0.2.3 from dependencies.
> chore(deps-dev): upgrades to Jest and Cypress to remove insecure json-schema version

- monitoring/package.json
- monitoring/yarn.lock
bumping the version of aws-sdk/client-cloudwatch to lift the version of fast-xml-parser since we can't create an easy resolution without affecting other deps.
fast-xml-parser version@4.0.11 has a high security issue and the dependency has been upgraded from this version of client-cloudwatch (also fixes client-sts dep on the same vuln)
> test: fix fast-xml-parser by bumping aws-sdk/client-cloudwatch

- cypress.config.ts
- cypress/e2e/sourcepoint-aus.cy.js
- cypress/e2e/sourcepoint-ccpa.cy.js
- cypress/e2e/sourcepoint-tcfv2.cy.js
- cypress/utils.js
- package.json
- src/getConsentFor.ts
- yarn.lock
Upgrade:
- typescript@~4.9.5 to align with other repos
- cypress@^12.8.1
Cypress 12 now enforces [test isolation](https://www.cypress.io/blog/2022/12/06/announcing-cypress-12/#test-isolation-is-now-default). So I've also updated the e2e tests to not rely on previous test state and each test run initialises itself.
Upgrade all the things
I attempted to release #724 previously with a `chore!` but it did not trigger a major release and it is blocking https://github.com/guardian/frontend/pull/25892.
I'm overriding the semantic prefix here with `fix!` to force a major release.
> fix!: Upgrade Typescript ~4.9.5 & Cypress

- .releaserc.json
As described in https://github.com/guardian/commercial/pull/848 the conventionalcommits preset configuration for semantic-release stopped working for `!` with types (build, chore, ci, docs, style, refactor, perf, test) and now only works for fix or feat.
This change should fix the preset for all commit types so that commits with with a `!` should create a major release.
I've deliberately created a chore! commit to test this.
> chore!: fix semantic release conventional commits preset for ! syntax

- src/vendors.ts
Removed the Facebook vendor from the vendor list
It is being removed from our IAB list and therefore must be removed from this.
> fix: remove fb vendor from vendor list

- monitoring/src/check-page/tcfv2.ts
This change clears local storage as well as cookies before testing the second layer in cmp monitoring. 
Following an upgrade to our underlying CMP to 4.9.0, consent is lingering in local storage from the previous test of the first layer and clearing cookies only no longer clears the consent ready to test the second layer.
> test: fix broken monitoring after SP upgrade

- .github/workflows/gh-pages.yml
The job to deploy to gh_pages suddenly stopped working last week. 
On discussion with the DevX team it appears we need to add more permissions to the workflow to ensure that it has access to the token.
[GitHub Docs for assigning permissions to a specific job](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) and [GitHub's starter workflow pages](https://github.com/actions/starter-workflows/blob/main/pages/static.yml) suggested this set of permissions.
Moving to an enterprise account has made access to GITHUB_TOKEN more restrictive so we need to add permissions on a per job basis - ideally the minimum set of permissions required for the job to complete.
> test: added token permissions for gh-pages workflow

- .github/workflows/gh-pages.yml
Adding extra permissions for gh-page deploy.
Deploys have been failing since we moved to enterprise.
> test: permissions for gh-pages deploy

- .github/workflows/CI.yml
Adds explicit permissions to CI.yml in order that it can run the semantic-release process.
When we moved to GitHub Enterprise this stopped working.
Based on the example here: https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions
> fix: add explicit permissions to CI.yml

- .github/workflows/CI.yml
Adding contents:write to CI.yml 
An attempt to find the minimum set of permissions required to successfully complete a release after permissions became restricted.
> fix: test adding contents:write to ci permissions

- README.md
- package.json
- src/index.ts
- src/vendorDataManager.test.ts
- src/vendorDataManager.ts
- src/vendorStorageIds.ts
- src/vendors.ts
- yarn.lock
Make sure that cookies and localStorage set by vendors are removed if their consent is removed.
From the RFC:
> A recent user comment prompted us to re-examine the behaviour of cookies for users who initially accept, but then later decline consent on our website via the CMP.
> PECR regulation means that the user must take a clear and positive action to give their consent to non-essential cookies. We only set non-essential cookies, or launch the scripts that set non-essential cookies, after we’ve checked that consent has been given. This means users who never give consent never have non-essential cookies set.
> However if the user initially consents but then goes on to decline consent subsequently, we have no standard mechanism in place to remove already-set cookies. At the moment we see …
> feat: Implement vendor cookie and localStorage consent based deny list

- src/vendorDataManager.ts
[`requestIdleCallback` is not available in Safari](https://caniuse.com/requestidlecallback) (!), we need to handle the case that it's not there.
Shoutout to @emma-imber for noticing this in sentry!
> fix: handle missing requestIdleCallback in vendorDataMananger

- package.json
Updates incorrect peer dep for @guardian/labs-beta 		
This was missed in an earlier update.
> chore: fix incorrect libs peerdep

- src/onConsentChange.test.js
- src/tcfv2/api.test.js
- src/tcfv2/api.ts
The TCF v2.2 update further strengthens the TCF as a standard in the industry: revised purpose names and descriptions, introduced retention periods for all purposes, removed legitimate interest for purposes 3 to 6, the introduction of data categories used in conjunction with the purposes, support for legitimate interest claim urls, adding support for localized policy urls, deprecation of the __tcfapi command "getTCData" and introducing a more robust vendor compliance program.
https://trello.com/c/axpgteSv
"getTCData" has been deprecated.
> chore: Update Sourcepoint getTCData to addEventListener

- README.md
- src/vendors.ts
This changes the vendor id for Permutive from a custom vendor id to their IAB vendor id.  It also adds Magnite so that Commercial Dev can test.  This has been agreed with Data Privacy as long as Magnite is not actively used in production. 
The old custom Permutive vendor id needs to be removed.
There were 3 permutive vendor ids at one point and only 1 is current.  We need to change from the previous older one so it can be removed from the Sourcepoint vendor list.  As the new vendor has been in the vendor list for some time it will have gone through a repermission already.
Adding Magnite for testing only at this point.
> fix: change vendor id for Permutive, add Magnite

- .changeset/config.json
Change changeset access from restricted to public.
Fix release workflow
> fix: Update config.json

- .github/workflows/cmp-build-release.yml
- scripts/check-build-folders
This is a script that checks the "assets", "aus", "ccpa", "lib", "tcfv2", "types" are in the dist folder after a build.
To ensure the dist folder is exported correctly.
https://trello.com/c/aqnoEy63/1188-create-tests-to-check-the-dist-folder-in-cmp-after-build-to-prevent-issue-where-the-folders-are-not-exported-correctly
> Chore: Create test to check 'dist' build folder

- .github/PULL_REQUEST_TEMPLATE.md
Updating the pull_request_template to reflect new deploy process.
Maintain docs.
> Chore: Update PULL_REQUEST_TEMPLATE.md

- .vscode/settings.json
Change to VS Code settings file only.
Microsoft changed the value of the fields - these are apparently equivalent. 
[VS Code update notes](https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto)
> Update settings.json following vscode upgrade

- .github/dependabot.yml
Using exclude-patterns instead of ignore. 
The `ignore` param works on the package-ecosystem whilst `exclude-patterns` works on groups.
The `ignore` param failed to remove the inquirer from the monitoring group.
https://trello.com/c/lSCfUOYr
> Use exclude-patterns for monitoring group

- .changeset/spotty-kangaroos-change.md
- src/sourcepoint.test.js
- src/sourcepoint.ts
- src/stub.ts
- src/types/ccpa.ts
- src/types/window.d.ts
Removes __gpp stub from loading in CCPA.
This caused an issue with ads. This is a temporary removal and will be reinstated once it's been debugged.
Tested using about us to check the stubs loaded.
> Revoke gpp ccpa stub

- .changeset/chilled-trains-talk.md
- src/vendorStorageIds.ts
ComDev is making a change that will allow comscore to drop this first party cookie. https://github.com/guardian/commercial/pull/1313
By adding it here we can make sure it's removed if consent changes.
> add new comscore cookie to `vendorStorageIds`

- cdk/lib/monitoring.ts
- monitoring/src/check-page/ccpa.ts
Removes a possibly redundant reload call from the CCPA monitoring checkPages function.  It is believed that a reload is happening as part of onConsentChange and therefore this reload may be causing issues when run against production.
Since the PR to add a final parameter to onConsentChange and the equivalent PR on the commercial side were added, the CCPA (US) monitoring has been flaky.
My working assumption is that on clickingDoNotSellMyInfo the commercial code is doing a refresh as part of it's final callback parameter triggered by the onConsentChange event and our actively pushing another refresh onto the call stack is causing the error we're seeing.  We do not appear to have any missing awaits that might otherwise account for this error.  
Unfortunately, I am unable to check which …
> Fix flaky ccpa monitoring tests

- sourcepoint-ui/live/TCFv2/theguardianAmp TCFv2 first_layer.css
- sourcepoint-ui/live/TCFv2/theguardianDotCom TCFv2 first_layer.css
- sourcepoint-ui/live/TCFv2/theguardianandroid TCFv2 first_layer.css
- sourcepoint-ui/live/TCFv2/theguardianios TCFv2 first_layer.css
This backs up the CSS changes resulting from message updates to add the reject all button.
Because Sourcepoint does not have any form of version management, we are backing things up here in case of problems.
> Back up css following reject all launch

- .github/dependabot.yml
- cypress/e2e/sourcepoint-tcfv2.cy.js
Stop creating dependabot updates for the base directory.
Update failing test.
This was migrated to csnx and deprecated.
> Remove CMP App group due to package being deprecated.

- .github/workflows/monitoring-CI.yml
- cdk/lib/__snapshots__/monitoring.test.ts.snap
- cdk/lib/monitoring.ts
- monitoring/package.json
- monitoring/yarn.lock
- Update playwright
- Fixing the runtime version to previous Lambda Runtime ARN.
The automatic update is incompatible with playwright-aws-lambda
https://github.com/JupiterOne/playwright-aws-lambda/issues/74
Tested in CODE
> Fix Monitoring by defining the NodeJS runtime version

- .github/workflows/monitoring-CI.yml
- cdk/lib/monitoring.ts
Adding the runtime id to the cdk. Removing the runtime id secret
In this PR (https://github.com/guardian/consent-management-platform/pull/989), I added the lambda node js runtime id as a secret. This has made local testing more difficult without actually removing the id from the repo (monitoring cdk snapshot)
> Add runtime id to monitoring

- cdk/lib/__snapshots__/monitoring.test.ts.snap
- cdk/package.json
- cdk/yarn.lock
- Moved @guardian/cdk to devDependencies
- Updated @guardian/cdk and other peer dependencies (aws-cdk & aws-cdk-lib)
- Added wrap-ansi as resolution
- Defined a package manager and version
Tested in CODE.
- Dev-X recommended moving @guardian/cdk to devDependencies
- wrap-ansi was set to 7.0.0 to get around the following issue 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/consent-management-platform/consent-management-platform/cdk/node_modules/wrap-ansi/index.js from /home/runner/work/consent-management-platform/consent-management-platform/cdk/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /home/runner/work/consent-management-platform/consent-management-platform/cdk/node_modules/cliui/build/index.cjs to a dynamic …
```
> Migrate cdk to dev dependency

- .github/dependabot.yml
- .github/workflows/monitoring-CI.yml
- monitoring/localRun.ts
- monitoring/package.json
- monitoring/pnpm-lock.yaml
- monitoring/remoteRun.ts
Use the newest inquirer version which actually means using "@inquirer/prompts". Inquirer 9 only supported esm so we could not upgrade from 8 but the new "@inquirer/prompts" supports cjs again. The new "@inquirer/prompts" also has a different syntax, hence using the new syntax.
It will prevent future vulnerabilities in an old inquirer version. Inquirer changed to use @inquirer/prompts: https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%4010.0.0
> newer inquirer versions and type-check

- synthetics/src/jurisdiction-checks/tcfv2-basic.js
- synthetics/src/utils/cmp-checks.js
- synthetics/src/utils/config/config-builder.js
Using the correct value when checking the jurisdiction.
Remove optout check as it's inconsistent
The name was changed from CCPA to USNAT throughout the codebase.
Tested locally.
> fix: Swap USNat for CCPA
