- README.md
- package.json
- tc-validate.sh
This adds some useful information in the `README.md`. I've also tidied up the scripts in the `package.json`. I've removed the scripts associated with  publishing to NPM as I'd like to update and reintroduce these in a separate PR with some documentation.
> updated README.md

- src/cookies.ts
Small reafactor to `getShortDomain` just to make it cleaner.
> Refactor getShortDomain

- src/config.ts
> CMP_DOMAIN now depends on environment

- package.json
Version bump to 0.1.0-alpha.3 in preparation for package publishing.
> Version bump to 0.1.0-alpha.3

- src/config.ts
...to the correct Frontend endpoint, that updates automatically.
> Update IAB Vendor List link

- src/config.ts
...so it doesn't crash when running on server side.
> Hotfix: Check is document var is present

- src/types.ts
remove unused type AdPurposeEvent
> remove unused type AdPurposeEvent

- package.json
- src/cmp.ts
...that were missed by eslint.
> Added missing return types

- package.json
- src/index.ts
- Bumped version to 0.2.0
- Exposed the IAB config vars again
> Bumped version && exposed IAB config vars

- src/config.ts
Add CMP_LOGS_URL internal config item for later use.
> Add CMP_LOGS_URL

- src/cookies.test.ts
- src/cookies.ts
This PR removes exports that are no longer used outside this modules.
> Removing unnecessary exports

- README.md
- src/cmp-ui.test.ts
- src/cmp-ui.ts
- src/index.ts
> Rename canShow to shouldShow

- package.json
- src/store.ts
Update vendorlist.json url in PROD
> Update vendorlist.json url in PROD

- src/component/ConsentManagementPlatform.tsx
Remove console.log from `ConsentManagementPlatform.tsx`
> Remove console.log from ConsentManagementPlatform.tsx

- README.md
This PR updates the `README.md` to reflect latest version (`2.0.3`) of this library as the previous instructions were out of date.
> update README.md to reflect latest version

- src/component/ConsentManagementPlatform.tsx
- src/store.test.ts
- src/store.ts
Remove `.finally` from the code to avoid compatibility issues with MS Edge and IE. Updated tests to reflect changes.
> Remove .finally code

- src/component/ConsentManagementPlatform.tsx
- src/component/Modal.tsx
This PR updates the copy used to inform the user how they can change their consent settings for their current browser.
> Update copy related to changing the privacy settings

- .vscode/settings.json
- update eslint settings
- disable `organizeImports` if enabled globally
> update vscode settings 

- src/ccpa/sourcepoint-stub.js
- src/ccpa/sourcepoint.test.js
- src/ccpa/sourcepoint.ts
doesn't inject string into dom any more
> Inline the sourcepoint stub

- src/ccpa/sourcepoint.ts
- src/domain.ts
- src/mark.ts
stops cors errors on code
no cors errors
> Check full guardian domain

- dev/app.tsx
- package.json
- src/tcf/component/Banner.tsx
- yarn.lock
Updates the src-* packages we use to the latest version.
There are no changes to the UI after the update.
> Update src-* version to the latest release

- .editorconfig
- .prettierrc
- README.md
readme suggestions. inline was getting really noisy so apologies for PR. 
i've tried to keep it as terse and generic as possible, see what you reckon
> readme suggestions

- package.json
- rollup.config.js
- src/mark.ts
- yarn.lock
removes all `console` and `assert` calls from prod build
> strip debug from production build

- .editorconfig
- .prettierrc
- README.md
Reverts guardian/consent-management-platform#134
> Revert "Define CMP v4 API"

- src/ccpa/sourcepoint.ts
Move the script element creation code inside init so it doesn't mess with SSR projects.
> Move script element creation to inside init

- .github/workflows/CI.yml
- .gitignore
- package.json
- src/index.test.js
- src/onConsentChange.test.js
- yarn.lock
- add tests for main index file
- adds PR test coverage reporting
> TCFv2 index tests

- src/ccpa/core.ts
- src/ccpa/sourcepoint.ts
- src/index.ts
Changes the type of `showPrivacyManager` to be `() => void`.
> showPrivacyManager now has the correct type

- src/ccpa/sourcepoint.test.js
- src/index.test.js
- src/tcfv2/sourcepoint.test.js
- Adds sourcepoint unit tests to tcfv2 & ccpa
> Added sourcepoint tests to tcfv2 and ccpa

- .gitignore
- README.md
- dev/app.tsx
- package.json
- src/oldCmp.ts
- src/onConsentChange.ts
- src/types.d.ts
Adds the custom vendors to the onConsentChange callback
> Added custom vendors and eventStatus to the onConsentChange.ts

- dev/app.tsx
- package.json
- src/index.test.js
- src/index.ts
- src/onConsentChange.ts
- src/window.d.ts
- puts all exports on window and uses them if they exist
> commercial.dcr.js hotfix

- .eslintrc.json
- rollup.config.dev.js
- rollup.config.js
- src/ccpa/index.ts
- src/ccpa/sourcepoint.test.js
- src/ccpa/sourcepoint.ts
- src/index.test.js
- src/index.ts
- src/oldCmp.ts
- src/onConsentChange.test.js
- src/tcfv2/index.ts
- src/tcfv2/sourcepoint.test.js
- src/tcfv2/sourcepoint.ts
- src/window.d.ts
add fixable lint rule for import sorting
> Sort imports

- .babelrc.js
- babel.config.js
enables async etc in jest tests properly
> Transpile for node in jest

- src/onConsentChange.ts
- src/types/ccpa.ts
- src/types/index.ts
- src/types/tcfv2/CustomVendorConsents.ts
- src/types/tcfv2/TCData.ts
- src/types/tcfv2/index.ts
- src/types/window.d.ts
captures most of the type changes from #217.
mainly moves them all to one place. some other changes likely to follow in the final moving around of code
> Move types to one place

- README.md
- package.json
- yarn.lock
auto-generates a toc in the readme
i can't get the push hook to commit before pushing which is annoying, so for now you need to push again. looks like might be an issue https://github.com/typicode/husky/issues/689.
but we update the readme so infrequently currently it's too bad for now
> Readme toc

- src/getConsentFor.ts
updates a9 to latest sourcepoint id
> chore: update a9 id

- .github/workflows/CI.yml
- README.md
its much quieter and works nicely in commerical-core
> ci: user coveralls instead

- README.md
> docs: give examples of disabling the CMP

- src/aus/api.test.js
- src/aus/api.ts
- src/aus/sourcepoint.ts
- src/ccpa/api.ts
- src/onConsentChange.test.js
- src/tcfv2/api.ts
merging https://github.com/guardian/consent-management-platform/pull/360 to `main`
> fix: Await uspapi

- .eslintrc.js
- lib/flow-gen.js
- package.json
- tsconfig.build.json
- tsconfig.json
- yarn.lock
adds flow declaration files
still needed in frontend
> feat: add Flow types

- .github/workflows/PR.yml
- yarn.lock
> chore(dev): Bump dependencies 2021.08.10

- package.json
- yarn.lock
Adds another batched round of updates to please Dependabot.
Closes:
- https://github.com/guardian/consent-management-platform/pull/583
- https://github.com/guardian/consent-management-platform/pull/582
- https://github.com/guardian/consent-management-platform/pull/581
- https://github.com/guardian/consent-management-platform/pull/580
- https://github.com/guardian/consent-management-platform/pull/579
> chore: Dependabot batch

- monitoring/package.json
- monitoring/remoteRun.ts
- monitoring/tsconfig.eslint.json
- monitoring/yarn.lock
Adds a script to remotely invoke the monitoring lambdas in the available global regions.
So we can see what their results are!
> test: Add simple script to invoke lambda in available regions

- cdk/lib/monitoring.ts
Tiny code cleanup, no-op.
Clean code make happy.
> refactor: Remove unused comments

- .github/workflows/snyk.yml
- .gitignore
- cdk/package.json
- cdk/yarn.lock
Adds Snyk monitoring to ensure there are no vulnerabilities in this repo.
Improve security, fall in line with Guardian best practise.
> test: Add Snyk workflow

- .github/workflows/snyk-pr.yml
Adds Snyk PR workflow from https://github.com/guardian/.github/tree/main/.github/workflows#usage-1
Better security, stay up to date with best practise.
> test: Add Snyk PR workflow

- monitoring/README.md
- monitoring/package.json
- monitoring/yarn.lock
This updates the readme to improve installation
and changes dependencies to not have to rely on the parent node install
> test: Updating dependencies and readme for monitoring

- monitoring/README.md
The ReadMe file in the monitoring directory.
An easily accessible link to monitor the lambda's in different regions.
> docs: Added grafana link to readme file

- cdk/lib/__snapshots__/monitoring.test.ts.snap
- cdk/lib/monitoring.ts
- monitoring/package.json
- monitoring/src/check-page/aus.ts
- monitoring/src/check-page/ccpa.ts
- monitoring/src/check-page/common-functions.ts
- monitoring/src/check-page/tcfv2.ts
- monitoring/src/config.test.ts
- monitoring/src/config.ts
- monitoring/src/types.ts
- monitoring/src/utils/config-builder/config-builder.ts
- monitoring/yarn.lock
This PR monitors and logs the time to load the time to load a cmp banner in all locations.
There have been reports of long loading times in Australia. Hence, it's useful to measure/calculate the average time to compare regions.
> test: Monitor CMP Loading Time

- .github/CODEOWNERS
- CODEOWNERS
Update CODEOWNERS
- remove root duplicate CODEOWNERS file
- update `.github/CODEOWNERS` to switch to `@guardian/transparency-consent`
> chore: Update CODEOWNERS

- .github/workflows/CI.yml
the old one seemed to not have been updated in a while and was failing.
> chore(deps-dev): change provided github action for test runner

- .github/workflows/CI.yml
> chore(deps-dev): change provided github action for test runner (#705)

- .github/workflows/CI.yml
add permission to update checks and contents and pull-requests
> chore(deps-dev): update CI workflow permissions

- README.md
This is an almost empty PR to fix the failing tests by using a fresh clone of the repository.
Broken test in last PR merge
> test: testing

- package.json
- yarn.lock
Upgrade @guardian/libs@14.0.0 to resolve peer dep issues in https://github.com/guardian/frontend/pull/25892
This will create a major release
> chore!: Upgrade @guardian/libs@14.0.0

- src/vendors.ts
change ipsos: https://trello.com/c/lit9iJr3/758-remove-the-extra-ipsos-mori-vendor
> fix: Update vendors.ts

- README.md
Updating the README to ensure it is consistent with the current vendor list.
A human-readable list to make sure it is clear which vendors are currently available.
> chore: ensure readme up to date with current vendors

- src/vendors.ts
Add documentation what vendors.ts is for and what needs to be considered when changing it
To help future developers
> docs: add comments to explain the file

- docs/01-development-instructions.md
- monitoring/package.json
- monitoring/yarn.lock
Installed npm-run-all in monitoring to have one command to trigger all the test commands.
Add yarn validate to use npm-run-all
Updating docs to include testing
> docs: Update README to include text about Testing

- monitoring/src/check-page/aus.ts
- monitoring/src/check-page/ccpa.ts
- monitoring/src/check-page/tcfv2.ts
remove catch from try (catch) finally
Do not want to catch errors but want the lambda to fail
> test: remove monitoring catch

- .changeset/stupid-clocks-tickle.md
- src/vendors.ts
Adds prebidCustom vendor.
prebidCustom has been added as a custom vendor.
> Updating prebid vendor

- .github/workflows/monitoring-CI.yml
- monitoring/src/config.test.ts
- monitoring/src/config.ts
- monitoring/src/index.ts
> Refactor env vars

- monitoring/src/check-page/aus.ts
- monitoring/src/check-page/ccpa.ts
- monitoring/src/check-page/tcfv2.ts
Temporarily comment out AMP tests until fixed.
They're currently unreliable and sometimes fail to load cmp after clearing cookies.
> Temporarily comment out AMP tests

- .github/workflows/snyk-pr.yml
- .github/workflows/snyk.yml
Fixes the snyk action file by adding the input in uppercase.
The snyk pr requires the to be in uppercase
> Fix synk workflows.

- synthetics/src/jurisdiction-checks/tcfv2-row.js
- synthetics/src/utils/config/config-builder.js
- synthetics/src/utils/config/config-builder.test.js
- synthetics/src/utils/config/config-helper.js
- synthetics/src/utils/config/config-helper.test.js
- synthetics/src/utils/config/config-wrapper.test.js
- synthetics/src/utils/constants.js
- synthetics/src/utils/url-builder.js
Updates the name of the `TCFV2`  test to `TCFV2_ROW` and updating the places it's referenced.
To reflect, the different banners and regions.
> Updated name of `TCFV2` test to `TCFV2_ROW`
